version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    # command: go run main.go

  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: frontend/Dockerfile
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./frontend:/app/frontend
